"""Constants for the AlpicAir Modbus integration."""
from __future__ import annotations

DOMAIN = "alpicair"
DEFAULT_NAME = "AlpicAir рекуператор"
DEFAULT_PORT = 502
DEFAULT_SLAVE = 1
DEFAULT_SCAN_INTERVAL = 10
CONF_CONNECTION_TYPE = "connection_type"
CONNECTION_TCP = "tcp"
CONNECTION_SERIAL = "serial"
MODE_STANDBY = 0
MODE_BUILDING_PROTECTION = 1
MODE_ECONOMY = 2
MODE_COMFORT = 3
MODE_INTENSIVE = "intensive"
MODE_OPTIONS = {
    MODE_STANDBY: "Standby",
    MODE_BUILDING_PROTECTION: "Защита здания",
    MODE_ECONOMY: "Эконом",
    MODE_COMFORT: "Комфорт",
}
REG_SYSTEM_MODE = 1
REG_COMFORT_TEMPERATURE = 2
REG_ECONOMY_TEMPERATURE = 4
REG_BUILDING_PROTECTION_TEMPERATURE = 6
REG_INTENSIVE_TIME_SET = 14
REG_NIGHT_COOLING_START_HOURS = 25
REG_NIGHT_COOLING_START_MINS = 26
REG_NIGHT_COOLING_STOP_HOURS = 27
REG_NIGHT_COOLING_STOP_MINS = 28
REG_NIGHT_COOLING_START_EXTRACT = 29
REG_NIGHT_COOLING_STOP_EXTRACT = 30
REG_NIGHT_COOLING_START_OUTDOOR = 31
REG_NIGHT_COOLING_SETPOINT = 32
REG_ALARM_A = 200
REG_ALARM_B = 201
REG_ALARMS_RESET = 202
REG_AIR_FLOW_1_SUPPLY = 450
REG_AIR_FLOW_2_SUPPLY = 451
REG_AIR_FLOW_3_SUPPLY = 452
REG_AIR_FLOW_4_SUPPLY = 453
REG_AIR_FLOW_1_EXTRACT = 456
REG_AIR_FLOW_2_EXTRACT = 457
REG_AIR_FLOW_3_EXTRACT = 458
REG_AIR_FLOW_4_EXTRACT = 459
REG_SUPPLY_TEMPERATURE = 800
REG_EXTRACT_TEMPERATURE = 801
REG_EXHAUST_TEMPERATURE = 802
REG_OUTDOOR_TEMPERATURE = 803
REG_SUPPLY_FILTER_PRESSURE = 816
REG_EXTRACT_FILTER_PRESSURE = 817
REG_HEAT_EXCHANGER_PRESSURE = 818
REG_REMOTE_SYSTEM_MODE = 820
REG_SUPPLY_AIR_FLOW_PRESSURE = 821
REG_EXTRACT_AIR_FLOW_PRESSURE = 822
COIL_NIGHT_COOLING_FUNCTION = 4
COIL_INTENSIVE_AIR_FLOW = 5
TEMPERATURE_SCALE = 10
PERCENT_SCALE = 10
