"""Constants for AlpicAir Ventilation Unit (SALDA MCB 1.27 OEM)."""
DOMAIN="alpicair"
DEFAULT_PORT=502
DEFAULT_SLAVE=1
DEFAULT_NAME="AlpicAir"
CONF_SLAVE="slave"

# Holding registers (R/W)
REG_SYSTEM_MODE=1
REG_COMFORT_SETPOINT=2
REG_NC_START_HOUR=25
REG_NC_START_MIN=26
REG_NC_STOP_HOUR=27
REG_NC_STOP_MIN=28
REG_NC_START_EXTRACT_TEMP=29
REG_NC_STOP_EXTRACT_TEMP=30
REG_NC_STOP_OUTDOOR_TEMP=31
REG_NC_SUPPLY_SETPOINT=32
REG_FLOW_1_SUPPLY=450
REG_FLOW_2_SUPPLY=451
REG_FLOW_3_SUPPLY=452
REG_FLOW_4_SUPPLY=453
REG_FLOW_1_EXTRACT=456
REG_FLOW_2_EXTRACT=457
REG_FLOW_3_EXTRACT=458
REG_FLOW_4_EXTRACT=459

# Coils (R/W)
COIL_DRYNESS=3
COIL_NIGHT_COOLING=4
COIL_BOOST=5
COIL_FULL_RECIRC_PROTECTION=6
COIL_FULL_RECIRC_ECONOMY=7
COIL_FLOW_BY_RH=8

# Input registers (R)
IR_STATE=1
IR_INTENSIVE_TIME_LEFT=13
IR_REQUIRED_SUPPLY_TEMP=17
IR_SUPPLY_TEMP=18
IR_EXTRACT_TEMP=19
IR_EXHAUST_TEMP=20
IR_OUTDOOR_TEMP=21
IR_ALARM_COUNT=28
IR_FILTER_DAYS_LEFT=30
IR_SUPPLY_FLOW_1=77
IR_SUPPLY_FLOW_2=78
IR_SUPPLY_FLOW_3=79
IR_SUPPLY_FLOW_4=80
IR_EXTRACT_FLOW_1=83
IR_EXTRACT_FLOW_2=84
IR_EXTRACT_FLOW_3=85
IR_EXTRACT_FLOW_4=86
IR_SUPPLY_FILTER_PRESSURE=112
IR_EXTRACT_FILTER_PRESSURE=115
IR_HEAT_EXCHANGER_PRESSURE=118
IR_HEAT_TRANSFER_EFFICIENCY=125

# Discrete input summaries (R)
DI_CRITICAL_ALARM=188
DI_WARNING=189

MODE_OPTIONS={"Защита здания":1,"Эконом":2,"Комфорт":3,"Интенсивный обдув":None}
MODE_NAMES={0:"Выключено",1:"Защита здания",2:"Эконом",3:"Комфорт"}
SYSTEM_STATES={0:"Ожидание",1:"Защита здания",2:"Эконом",3:"Комфорт",4:"Аварийный режим",5:"Подготовка",6:"Открытие заслонок",7:"Форсаж",8:"Охлаждение нагревателей",9:"Закрытие заслонок",10:"Ночное охлаждение",11:"Критическая авария",12:"Пожарная тревога",13:"Защита от замерзания",14:"Замена фильтров",15:"Ограничение скорости",17:"Тест заслонки"}

# Actual device range: 160..300 *0.1 C, using user-friendly UI limits.
COMFORT_MIN=15.0
COMFORT_MAX=25.0
